library(jaffelab)
library(SummarizedExperiment)
library(limma)
library(edgeR)
library('devtools')
library(recount)

setwd('/dcl02/lieber/ptsd/RNAseq/VA_PTSD_RNAseq/')
load("rdas/dACC/geneStats_DE_qSVA_sensitivity_antidepressants_dACC_threeGroup_antideptox.rda")
dACC_antidepress <- geneStats_dACC_antideptox
load('rdas/dACC/geneStats_DE_qSVA_dACC_threeGroup.rda')
dACC_MDD <- summary(lm(dACC_antidepress$logFC_AntidepTox~dACC_antidepress$logFC_MDD))
dACC_MDD2 <- summary(lm(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_MDD~geneStats_dACC$logFC_MDD))
dACC_PTSD <- summary(lm(dACC_antidepress$logFC_AntidepTox~dACC_antidepress$logFC_PTSD))
dACC_PTSD2 <- summary(lm(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSD~geneStats_dACC$logFC_PTSD))
dACC_onlyPTSD <- summary(lm(dACC_antidepress$logFC_AntidepTox~dACC_antidepress$logFC_onlyPTSD))
dACC_onlyPTSD2 <- summary(lm(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_onlyPTSD~geneStats_dACC$logFC_onlyPTSD))
dACC_PTSDvsMDD <- summary(lm(dACC_antidepress$logFC_AntidepTox~dACC_antidepress$logFC_PTSDvsMDD))
dACC_PTSDvsMDD2 <- summary(lm(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSDvsMDD~geneStats_dACC$logFC_PTSDvsMDD))


pdf('pdf/Sensitivity_Analyses/antidepressants_sensitivity_moreinfo.pdf',useDingbats = FALSE)
plot(dACC_antidepress$logFC_AntidepTox, dACC_antidepress$logFC_MDD, xlab = "Including Antidepressants (tox) log2FC Antidep", ylab="Including Antidepressants (tox) log2FC MDD", main = "dACC MDD")
abline(h=mean(dACC_antidepress$logFC_MDD), v=mean(dACC_antidepress$logFC_AntidepTox), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_MDD$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_MDD,geneStats_dACC$logFC_MDD, xlab = "Including Antidepressants (tox) log2FC MDD + Antidep", ylab="Original log2FC MDD", main = "dACC MDD")
abline(h=mean(geneStats_dACC$logFC_MDD), v=mean(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_MDD), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_MDD2$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox, dACC_antidepress$logFC_PTSD, xlab = "Including Antidepressants (tox) log2FC Antidep", ylab="Including Antidepressants (tox) log2FC PTSD", main = "dACC PTSD")
abline(h=mean(dACC_antidepress$logFC_PTSD), v=mean(dACC_antidepress$logFC_AntidepTox), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_PTSD$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSD,geneStats_dACC$logFC_PTSD, xlab = "Including Antidepressants (tox) log2FC PTSD + Antidep", ylab="Original log2FC PTSD", main = "dACC PTSD")
abline(h=mean(geneStats_dACC$logFC_PTSD), v=mean(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSD), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_PTSD2$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox, dACC_antidepress$logFC_onlyPTSD, xlab = "Including Antidepressants (tox) log2FC Antidep", ylab="Including Antidepressants (tox) log2FC onlyPTSD", main = "dACC onlyPTSD")
abline(h=mean(dACC_antidepress$logFC_onlyPTSD), v=mean(dACC_antidepress$logFC_AntidepTox), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_onlyPTSD$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_onlyPTSD,geneStats_dACC$logFC_onlyPTSD, xlab = "Including Antidepressants (tox) log2FC onlyPTSD + Antidep", ylab="Original log2FC onlyPTSD", main = "dACC onlyPTSD")
abline(h=mean(geneStats_dACC$logFC_onlyPTSD), v=mean(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_onlyPTSD), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_onlyPTSD2$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox, dACC_antidepress$logFC_PTSDvsMDD, xlab = "Including Antidepressants (tox) log2FC Antidep", ylab="Including Antidepressants (tox) log2FC PTSDvsMDD", main = "dACC PTSDvsMDD")
abline(h=mean(dACC_antidepress$logFC_PTSDvsMDD), v=mean(dACC_antidepress$logFC_AntidepTox), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_PTSDvsMDD$adj.r.squared, digits=3)))
plot(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSDvsMDD,geneStats_dACC$logFC_PTSDvsMDD, xlab = "Including Antidepressants (tox) log2FC PTSDvsMDD + Antidep", ylab="Original log2FC PTSDvsMDD", main = "dACC PTSDvsMDD")
abline(h=mean(geneStats_dACC$logFC_PTSDvsMDD), v=mean(dACC_antidepress$logFC_AntidepTox+dACC_antidepress$logFC_PTSDvsMDD), col="purple")
legend("bottomright", bty="n", legend=paste("R2 = ", format(dACC_PTSDvsMDD2$adj.r.squared, digits=3)))
dev.off()